### ISSUE TITLE
#ask

### ISSUE THREAD

**Issue by MFarelS** [nvmbrxi/nvmbrxi.github.io#1]
GitHub Pages ndak support .php setauku

Jadi apa gunanya file .php??

**Comment by MFarelS** [comment]
> GitHub Pages ndak support .php setauku
> 
> Jadi gunanya file yang .php apa??

**Comment by nvmbrxi** [comment]
buat numpang host aja biar bisa codenya bisa diliat.

**Comment by MFarelS** [comment]
Owalah okeh
